require:
  - rubocop-performance
  - rubocop-minitest
  - rubocop-rake

AllCops:
  # Exclude directories like vendor/bundle, logs, etc.
  Exclude:
    - "vendor/**/*"
    - "db/schema.rb"
    - "config/**/*"
    - "Rakefile" # Often excluded

Layout/LineLength:
  Max: 80 # Allow lines up to 120 characters

Metrics/MethodLength:
  Max: 30 # Keep methods relatively short

Metrics/BlockLength:
  Max: 30 # Limit block length to keep them manageable

Style/Documentation:
  Enabled: false # Disable the requirement for documentation comments (optional)
