name: CI Test

on:
  push:
    branches: [main]
    paths:
      - 'lib/**'
      - 'test/**'
  pull_request:
    branches: [main]
    paths:
      - 'lib/**'
      - 'test/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4'
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Run tests
        run: bundle exec rake test
